// <auto-generated />
using System;
using GraphQL.ElectronicsStore.API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQL.ElectronicsStore.API.Services.Migrations
{
    [DbContext(typeof(ElectronicsStoreDbContext))]
    [Migration("20240917230359_addingQuantityToProducts")]
    partial class addingQuantityToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ElectronicsStore")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.CategoryDTO", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", "ElectronicsStore");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Home Entertainment"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Televisions"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Home Theater Systems"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "DVD/Blu-ray Players"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Streaming Devices"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Soundbars and Speakers"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Computers and Accessories"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Laptops"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Desktop PCs"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Monitors"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Printers and Scanners"
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Keyboards, Mice, and Trackpads"
                        },
                        new
                        {
                            CategoryID = 13,
                            CategoryName = "External Hard Drives and SSDs"
                        },
                        new
                        {
                            CategoryID = 14,
                            CategoryName = "USB Flash Drives"
                        },
                        new
                        {
                            CategoryID = 15,
                            CategoryName = "Routers and Modems"
                        },
                        new
                        {
                            CategoryID = 16,
                            CategoryName = "Mobile Devices"
                        },
                        new
                        {
                            CategoryID = 17,
                            CategoryName = "Smartphones"
                        },
                        new
                        {
                            CategoryID = 18,
                            CategoryName = "Tablets"
                        },
                        new
                        {
                            CategoryID = 19,
                            CategoryName = "Smartwatches"
                        },
                        new
                        {
                            CategoryID = 20,
                            CategoryName = "E-Readers"
                        },
                        new
                        {
                            CategoryID = 21,
                            CategoryName = "Mobile Accessories"
                        },
                        new
                        {
                            CategoryID = 22,
                            CategoryName = "Wearables and Fitness Gadgets"
                        },
                        new
                        {
                            CategoryID = 23,
                            CategoryName = "Smartwatches"
                        },
                        new
                        {
                            CategoryID = 24,
                            CategoryName = "Fitness Trackers"
                        },
                        new
                        {
                            CategoryID = 25,
                            CategoryName = "Virtual Reality Headsets"
                        },
                        new
                        {
                            CategoryID = 26,
                            CategoryName = "Audio Equipment"
                        },
                        new
                        {
                            CategoryID = 27,
                            CategoryName = "Headphones"
                        },
                        new
                        {
                            CategoryID = 28,
                            CategoryName = "Kitchen Room"
                        },
                        new
                        {
                            CategoryID = 29,
                            CategoryName = "Laundry Room"
                        },
                        new
                        {
                            CategoryID = 30,
                            CategoryName = "Photography"
                        },
                        new
                        {
                            CategoryID = 31,
                            CategoryName = "Video Camera"
                        },
                        new
                        {
                            CategoryID = 32,
                            CategoryName = "Gaming Consoles"
                        },
                        new
                        {
                            CategoryID = 33,
                            CategoryName = "Gaming Accessories"
                        });
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.CustomerDTO", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers", "ElectronicsStore");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "1234 Coral Way, Miami, FL 33145",
                            Email = "AlbertoSmith1785@gmail.com",
                            FirstName = "Alberto",
                            LastName = "Smith",
                            Phone = "+57 3126555555"
                        });
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.OrderDTO", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 9, 17, 18, 3, 57, 960, DateTimeKind.Local).AddTicks(2180));

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders", "ElectronicsStore");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.OrderProductDTO", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderProducts", "ElectronicsStore");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.ProductCategoryDTO", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ProductCategories", "ElectronicsStore");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 1,
                            CategoryID = 2
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 3
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 4
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 5
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 6
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 26
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 8
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 9
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 10
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 11
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 12
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 13
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 14
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 15
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 16
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 17
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 16
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 18
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 19
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 22
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 20
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 21
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 22
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 24
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 25
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 26
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 27
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 26
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 27
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 26
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 26
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 30
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 31
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 30
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 30
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 7
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 13
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 32
                        },
                        new
                        {
                            ProductID = 31,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 31,
                            CategoryID = 32
                        },
                        new
                        {
                            ProductID = 32,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 32,
                            CategoryID = 32
                        },
                        new
                        {
                            ProductID = 33,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 33,
                            CategoryID = 33
                        },
                        new
                        {
                            ProductID = 34,
                            CategoryID = 26
                        },
                        new
                        {
                            ProductID = 34,
                            CategoryID = 33
                        },
                        new
                        {
                            ProductID = 35,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 36,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 36,
                            CategoryID = 28
                        },
                        new
                        {
                            ProductID = 37,
                            CategoryID = 29
                        },
                        new
                        {
                            ProductID = 38,
                            CategoryID = 29
                        },
                        new
                        {
                            ProductID = 39,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 39,
                            CategoryID = 28
                        });
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.ProductDTO", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products", "ElectronicsStore");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Description = "Vivid 55-inch 4K display with smart streaming capabilities.",
                            ImageUrl = "https://smselectronic.com/wp-content/uploads/2024/06/SAMSUNG-TV-55-QLED-4K-Q60C-1.png",
                            Price = 499.99m,
                            ProductName = "Samsung 55-Inch Smart TV",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 2,
                            Description = "Premium surround sound for an immersive home cinema experience.",
                            ImageUrl = "https://m.media-amazon.com/images/I/51m4NsZau4L._AC_SL1212_.jpg",
                            Price = 299.99m,
                            ProductName = "Sony Home Theater System",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 3,
                            Description = "Blu-ray player with smooth playback and advanced upscaling.",
                            ImageUrl = "https://www.lg.com/content/dam/channel/wcms/pe/images/video/bp325/gallery/medium.jpg",
                            Price = 79.99m,
                            ProductName = "LG Blu-ray Player",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 4,
                            Description = "Compact streaming stick with 4K streaming and remote.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71wrIZujPIL.jpg",
                            Price = 49.99m,
                            ProductName = "Roku Streaming Stick",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = 5,
                            Description = "High-end soundbar delivering exceptional clarity and deep bass.",
                            ImageUrl = "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/bose_soundbar_700/product_silo_images/bose_soundbar_700_black_EC_03.psd/jcr:content/renditions/cq5dam.web.1920.1920.png",
                            Price = 799.99m,
                            ProductName = "Bose Soundbar 700",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductID = 6,
                            Description = "Ultra-thin, powerful laptop with stunning 13-inch display.",
                            ImageUrl = "https://m.media-amazon.com/images/I/710EGJBdIML._AC_SL1500_.jpg",
                            Price = 1099.99m,
                            ProductName = "Dell XPS 13 Laptop",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 7,
                            Description = "Reliable desktop PC for home and office productivity.",
                            ImageUrl = "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c07920872.png?impolicy=Png_Res",
                            Price = 649.99m,
                            ProductName = "HP Desktop PC",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 8,
                            Description = "27-inch monitor with crisp Full HD visuals for work or gaming.",
                            ImageUrl = "https://symcomputadores.com/wp-content/uploads/2024/08/Acer-EK271-E-27Acer-EK271-E.png",
                            Price = 199.99m,
                            ProductName = "Acer 27-Inch Monitor",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 9,
                            Description = "Efficient laser printer with high-quality print outputs.",
                            ImageUrl = "https://pcsoftwareus.com/wp-content/uploads/2022/10/Canon-Laser-MF232W-web-1.jpg",
                            Price = 149.99m,
                            ProductName = "Canon Laser Printer",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 10,
                            Description = "Ergonomic wireless keyboard for smooth typing experience.",
                            ImageUrl = "https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/combos/mk520/gallery/mk520-gallery-1-new.png?v=1",
                            Price = 59.99m,
                            ProductName = "Logitech Wireless Keyboard",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductID = 11,
                            Description = "Portable 1TB hard drive for easy data backups and transfers.",
                            ImageUrl = "https://mac-center.com/cdn/shop/products/156e18327d1a5b4d1ca7cbd8a3939b3f-product_817f4ef5-86cb-4521-8d4b-1bac846601db.webp?v=1681388624",
                            Price = 59.99m,
                            ProductName = "Seagate 1TB External Hard Drive",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 12,
                            Description = "Compact and reliable 128GB USB for secure file storage.",
                            ImageUrl = "https://www.tecnoflash.com.co/wp-content/uploads/2024/08/Memoria-Sandisk-Usb-128Gb.png",
                            Price = 19.99m,
                            ProductName = "SanDisk 128GB USB Flash Drive",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductID = 13,
                            Description = "Fast WiFi 6 router with wide coverage and high speeds.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGiDspwjQwHqM9DsLxgfPNIhUSKVx83yLTDQ&s",
                            Price = 99.99m,
                            ProductName = "TP-Link WiFi 6 Router",
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductID = 14,
                            Description = "Advanced iPhone with high-resolution camera and fast performance.",
                            ImageUrl = "https://www.compudemano.com/wp-content/uploads/2023/01/apple-iphone-14-plus-128gb-blanco-estelar.jpg",
                            Price = 999.99m,
                            ProductName = "Apple iPhone 14",
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductID = 15,
                            Description = "Powerful tablet with stunning display and S Pen support.",
                            ImageUrl = "https://www.manuales.com.co/thumbs/products/l/1260236-samsung-galaxy-tab-s7.webp",
                            Price = 649.99m,
                            ProductName = "Samsung Galaxy Tab S7",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 16,
                            Description = "Feature-packed smartwatch with advanced health monitoring.",
                            ImageUrl = "https://www.compudemano.com/wp-content/uploads/2022/10/apple-watch-serires-8-45mm-gps-blanco-estelar.png",
                            Price = 399.99m,
                            ProductName = "Apple Watch Series 8",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 17,
                            Description = "E-reader with crisp display and weeks-long battery life.",
                            ImageUrl = "https://m.media-amazon.com/images/G/01/kindle/journeys/5xlDnKG94P0ryVnD8MqFmnIhMKBXE2F2BxyzUQHa63Hhs3D/ZjBjZWUxMjIt._CB641064212_.jpg",
                            Price = 129.99m,
                            ProductName = "Amazon Kindle Paperwhite",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 18,
                            Description = "High-capacity power bank for fast and reliable charging on the go.",
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_881019-MCO73793450400_012024-O.webp",
                            Price = 49.99m,
                            ProductName = "Anker Power Bank 20000mAh",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 19,
                            Description = "Fitness tracker with health metrics and long battery life.",
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_883919-MLU70662175641_072023-O.webp",
                            Price = 149.99m,
                            ProductName = "Fitbit Charge 5",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 20,
                            Description = "VR headset with immersive experiences and wireless connectivity.",
                            ImageUrl = "https://i5.walmartimages.com/seo/Meta-Oculus-Quest-2-64GB-Advanced-All-In-One-Virtual-Reality-Headset_16a9974e-a5b0-4cad-a98e-730148409bef.3e8858a1d3beb01ff2fbc79a880beedf.jpeg",
                            Price = 299.99m,
                            ProductName = "Oculus Quest 2 VR Headset",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductID = 21,
                            Description = "Noise-canceling headphones for clear, immersive sound.",
                            ImageUrl = "https://www.sony.com/image/eb0062b3db03748efc7f5ca3fd82ccc5?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF",
                            Price = 249.99m,
                            ProductName = "Sony Noise-Canceling Headphones",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 22,
                            Description = "Premium wireless earbuds with noise cancellation.",
                            ImageUrl = "https://mac-center.com/cdn/shop/files/IMG-10869228.jpg?v=1723753366",
                            Price = 199.99m,
                            ProductName = "Apple AirPods Pro",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = 23,
                            Description = "Portable speaker with deep bass and high-quality sound.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YL9rMWkmPTAenjc9r2Qnv1NThoLhTK6Y5A&s",
                            Price = 99.99m,
                            ProductName = "JBL Bluetooth Speaker",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 24,
                            Description = "Voice-controlled smart speaker with rich sound.",
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_897798-MCO53950787380_022023-O.webp",
                            Price = 199.99m,
                            ProductName = "Sonos One Smart Speaker",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 25,
                            Description = "Entry-level DSLR for high-quality photos and videos.",
                            ImageUrl = "https://eoatecnologia.com/cdn/shop/files/1535598024_IMG_1056607.jpg?v=1699992619&width=416",
                            Price = 499.99m,
                            ProductName = "Nikon D3500 DSLR Camera",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductID = 26,
                            Description = "Rugged action camera for capturing extreme moments.",
                            ImageUrl = "https://www.artikulos.co/wp-content/uploads/GoPro-HERO-11-Black-en-ARTIKULOS.CO-Foto-1.jpg",
                            Price = 349.99m,
                            ProductName = "GoPro Hero 11 Action Camera",
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductID = 27,
                            Description = "Prime lens for sharp, fast, and versatile photography.",
                            ImageUrl = "https://lumen-colombia.com/8337-large_01oslo/canon-50mm.jpg",
                            Price = 125.99m,
                            ProductName = "Canon 50mm f/1.8 Lens",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 28,
                            Description = "Durable tripod for steady shots and easy handling.",
                            ImageUrl = "https://cassaimportadores.com/cdn/shop/products/Manfrotto-TrIpode-de-aluminio-Compact-Action-con-cabezal-hibrido_1200x1200.png?v=1634751589",
                            Price = 89.99m,
                            ProductName = "Manfrotto Tripod",
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductID = 29,
                            Description = "High-speed 64GB SD card for fast data transfer.",
                            ImageUrl = "https://importacionesarturia.com/wp-content/uploads/2020/04/Memoria-Sandisk-64Gb-de-100mbs-PgBlanca-2.jpg",
                            Price = 19.99m,
                            ProductName = "SanDisk 64GB SD Card",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 30,
                            Description = "Next-gen gaming console with stunning 4K visuals.",
                            ImageUrl = "https://exitocol.vtexassets.com/arquivos/ids/9154830/consola-sony-playstation-5-ps5-825gb-lector-de-disco.jpg?v=637631028235770000",
                            Price = 499.99m,
                            ProductName = "PlayStation 5 Console",
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductID = 31,
                            Description = "Powerful gaming console for a seamless experience.",
                            ImageUrl = "https://exitocol.vtexassets.com/arquivos/ids/7234188/consola-xbox-series-x-1tb-microsoft.jpg?v=637532554328630000",
                            Price = 499.99m,
                            ProductName = "Xbox Series X Console",
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductID = 32,
                            Description = "Portable gaming console for on-the-go fun.",
                            ImageUrl = "https://imagedelivery.net/4fYuQyy-r8_rpBpcY7lH_A/falabellaCO/126171770_01/w=800,h=800,fit=pad",
                            Price = 299.99m,
                            ProductName = "Nintendo Switch",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 33,
                            Description = "Innovative controller with haptic feedback for PS5.",
                            ImageUrl = "https://cosonyb2c.vtexassets.com/arquivos/ids/345373/PS5_DS_Pshot_A.jpg?v=637363940945300000",
                            Price = 69.99m,
                            ProductName = "PS5 DualSense Controller",
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 34,
                            Description = "Wireless headset for immersive Xbox gaming audio.",
                            ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_839906-MLU70065296481_062023-O.webp",
                            Price = 99.99m,
                            ProductName = "Xbox Wireless Headset",
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 35,
                            Description = "Automated vacuum with smart navigation for cleaning.",
                            ImageUrl = "https://www.irobotcolombia.com/wp-content/uploads/2023/01/j7.jpg",
                            Price = 299.99m,
                            ProductName = "iRobot Roomba Vacuum",
                            StockQuantity = 14
                        },
                        new
                        {
                            ProductID = 36,
                            Description = "Energy-efficient air conditioner with smart controls.",
                            ImageUrl = "https://www.lg.com/africa/images/split-air-conditioners/md06099357/gallery/medium02.jpg",
                            Price = 599.99m,
                            ProductName = "LG Smart Air Conditioner",
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductID = 37,
                            Description = "Front load washing machine with fast and efficient cleaning.",
                            ImageUrl = "https://images.samsung.com/is/image/samsung/p6pim/in/ww80t4040ce-tl/gallery/in-front-loading-washer-ww70t4020cheo-377223-ww80t4040ce-tl-395196808?$650_519_PNG$",
                            Price = 849.99m,
                            ProductName = "Samsung Front Load Washing Machine",
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductID = 38,
                            Description = "Spacious refrigerator with adjustable temperature controls.",
                            ImageUrl = "https://i5.walmartimages.com/seo/Whirlpool-33-21-cu-ft-Top-Freezer-Refrigerator-in-Monochromatic-Stainless-Steel_83b13732-b9d5-40fd-87ce-9f15a4462f8e.9a4cc30a642274ffb600d70c10c0416b.jpeg",
                            Price = 1199.99m,
                            ProductName = "Whirlpool Refrigerator",
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductID = 39,
                            Description = "High-performance microwave oven for quick and easy cooking.",
                            ImageUrl = "https://www.panasonic.com/content/dam/pim/my/en/NN/NN-ST2/NN-ST253/NN-ST253-Product_ImageGlobal-1_my_en.png",
                            Price = 129.99m,
                            ProductName = "Panasonic Microwave Oven",
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.OrderDTO", b =>
                {
                    b.HasOne("GraphQL.ElectronicsStore.API.Services.DTOs.CustomerDTO", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.OrderProductDTO", b =>
                {
                    b.HasOne("GraphQL.ElectronicsStore.API.Services.DTOs.OrderDTO", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphQL.ElectronicsStore.API.Services.DTOs.ProductDTO", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.ProductCategoryDTO", b =>
                {
                    b.HasOne("GraphQL.ElectronicsStore.API.Services.DTOs.CategoryDTO", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphQL.ElectronicsStore.API.Services.DTOs.ProductDTO", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.CategoryDTO", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.CustomerDTO", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.OrderDTO", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("GraphQL.ElectronicsStore.API.Services.DTOs.ProductDTO", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
