using GraphQL.ElectronicsStore.API.Services.DTOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Reflection.Emit;

namespace GraphQL.ElectronicsStore.API.Services.Config
{
    public class ProductConfig : IEntityTypeConfiguration<ProductDTO>
    {
        public void Configure(EntityTypeBuilder<ProductDTO> builder)
        {
            builder.HasKey(p => p.ProductID);
            builder.Property(p => p.ProductID).UseIdentityColumn();
            builder.Property(p => p.ProductName).IsRequired().HasMaxLength(100);
            builder.Property(p => p.Price).IsRequired();
            builder.Property(p => p.StockQuantity).IsRequired();
            builder.Property(p => p.ImageUrl).HasMaxLength(400);
            builder.Property(p => p.Description).HasMaxLength(100);
            builder.HasData(new List<ProductDTO>() {
                new() { ProductID = 1, ProductName = "Samsung 55-Inch Smart TV", Price = 499.99m, StockQuantity = 25, ImageUrl = "https://smselectronic.com/wp-content/uploads/2024/06/SAMSUNG-TV-55-QLED-4K-Q60C-1.png", Description = "Vivid 55-inch 4K display with smart streaming capabilities." },
                new() { ProductID = 2, ProductName = "Sony Home Theater System", Price = 299.99m, StockQuantity = 15, ImageUrl = "https://m.media-amazon.com/images/I/51m4NsZau4L._AC_SL1212_.jpg", Description = "Premium surround sound for an immersive home cinema experience."  },
                new() { ProductID = 3, ProductName = "LG Blu-ray Player", Price = 79.99m, StockQuantity = 30 , ImageUrl = "https://www.lg.com/content/dam/channel/wcms/pe/images/video/bp325/gallery/medium.jpg", Description = "Blu-ray player with smooth playback and advanced upscaling." },
                new() { ProductID = 4, ProductName = "Roku Streaming Stick", Price = 49.99m, StockQuantity = 40 , ImageUrl = "https://m.media-amazon.com/images/I/71wrIZujPIL.jpg", Description = "Compact streaming stick with 4K streaming and remote." },
                new() { ProductID = 5, ProductName = "Bose Soundbar 700", Price = 799.99m, StockQuantity = 10 , ImageUrl = "https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/speakers/bose_soundbar_700/product_silo_images/bose_soundbar_700_black_EC_03.psd/jcr:content/renditions/cq5dam.web.1920.1920.png", Description = "High-end soundbar delivering exceptional clarity and deep bass." },
                new() { ProductID = 6, ProductName = "Dell XPS 13 Laptop", Price = 1099.99m, StockQuantity = 20 , ImageUrl = "https://m.media-amazon.com/images/I/710EGJBdIML._AC_SL1500_.jpg", Description = "Ultra-thin, powerful laptop with stunning 13-inch display." },
                new() { ProductID = 7, ProductName = "HP Desktop PC", Price = 649.99m, StockQuantity = 18 , ImageUrl = "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c07920872.png?impolicy=Png_Res", Description = "Reliable desktop PC for home and office productivity." },
                new() { ProductID = 8, ProductName = "Acer 27-Inch Monitor", Price = 199.99m, StockQuantity = 22 , ImageUrl = "https://symcomputadores.com/wp-content/uploads/2024/08/Acer-EK271-E-27Acer-EK271-E.png", Description = "27-inch monitor with crisp Full HD visuals for work or gaming." },
                new() { ProductID = 9, ProductName = "Canon Laser Printer", Price = 149.99m, StockQuantity = 25 , ImageUrl = "https://pcsoftwareus.com/wp-content/uploads/2022/10/Canon-Laser-MF232W-web-1.jpg", Description = "Efficient laser printer with high-quality print outputs." },
                new() { ProductID = 10, ProductName = "Logitech Wireless Keyboard", Price = 59.99m, StockQuantity = 35 , ImageUrl = "https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/combos/mk520/gallery/mk520-gallery-1-new.png?v=1", Description = "Ergonomic wireless keyboard for smooth typing experience." },
                new() { ProductID = 11, ProductName = "Seagate 1TB External Hard Drive", Price = 59.99m, StockQuantity = 50 , ImageUrl = "https://mac-center.com/cdn/shop/products/156e18327d1a5b4d1ca7cbd8a3939b3f-product_817f4ef5-86cb-4521-8d4b-1bac846601db.webp?v=1681388624", Description = "Portable 1TB hard drive for easy data backups and transfers." },
                new() { ProductID = 12, ProductName = "SanDisk 128GB USB Flash Drive", Price = 19.99m, StockQuantity = 75 , ImageUrl = "https://www.tecnoflash.com.co/wp-content/uploads/2024/08/Memoria-Sandisk-Usb-128Gb.png", Description = "Compact and reliable 128GB USB for secure file storage." },
                new() { ProductID = 13, ProductName = "TP-Link WiFi 6 Router", Price = 99.99m, StockQuantity = 28 , ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGiDspwjQwHqM9DsLxgfPNIhUSKVx83yLTDQ&s", Description = "Fast WiFi 6 router with wide coverage and high speeds."},
                new() { ProductID = 14, ProductName = "Apple iPhone 14", Price = 999.99m, StockQuantity = 12 , ImageUrl = "https://www.compudemano.com/wp-content/uploads/2023/01/apple-iphone-14-plus-128gb-blanco-estelar.jpg", Description = "Advanced iPhone with high-resolution camera and fast performance." },
                new() { ProductID = 15, ProductName = "Samsung Galaxy Tab S7", Price = 649.99m, StockQuantity = 15 , ImageUrl = "https://www.manuales.com.co/thumbs/products/l/1260236-samsung-galaxy-tab-s7.webp", Description = "Powerful tablet with stunning display and S Pen support." },
                new() { ProductID = 16, ProductName = "Apple Watch Series 8", Price = 399.99m, StockQuantity = 20 , ImageUrl = "https://www.compudemano.com/wp-content/uploads/2022/10/apple-watch-serires-8-45mm-gps-blanco-estelar.png", Description = "Feature-packed smartwatch with advanced health monitoring." },
                new() { ProductID = 17, ProductName = "Amazon Kindle Paperwhite", Price = 129.99m, StockQuantity = 18 , ImageUrl = "https://m.media-amazon.com/images/G/01/kindle/journeys/5xlDnKG94P0ryVnD8MqFmnIhMKBXE2F2BxyzUQHa63Hhs3D/ZjBjZWUxMjIt._CB641064212_.jpg", Description = "E-reader with crisp display and weeks-long battery life." },
                new() { ProductID = 18, ProductName = "Anker Power Bank 20000mAh", Price = 49.99m, StockQuantity = 50 , ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_881019-MCO73793450400_012024-O.webp", Description = "High-capacity power bank for fast and reliable charging on the go." },
                new() { ProductID = 19, ProductName = "Fitbit Charge 5", Price = 149.99m, StockQuantity = 22 , ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_883919-MLU70662175641_072023-O.webp", Description = "Fitness tracker with health metrics and long battery life." },
                new() { ProductID = 20, ProductName = "Oculus Quest 2 VR Headset", Price = 299.99m, StockQuantity = 10 , ImageUrl = "https://i5.walmartimages.com/seo/Meta-Oculus-Quest-2-64GB-Advanced-All-In-One-Virtual-Reality-Headset_16a9974e-a5b0-4cad-a98e-730148409bef.3e8858a1d3beb01ff2fbc79a880beedf.jpeg", Description = "VR headset with immersive experiences and wireless connectivity." },
                new() { ProductID = 21, ProductName = "Sony Noise-Canceling Headphones", Price = 249.99m, StockQuantity = 30 , ImageUrl = "https://www.sony.com/image/eb0062b3db03748efc7f5ca3fd82ccc5?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF", Description = "Noise-canceling headphones for clear, immersive sound." },
                new() { ProductID = 22, ProductName = "Apple AirPods Pro", Price = 199.99m, StockQuantity = 40 , ImageUrl = "https://mac-center.com/cdn/shop/files/IMG-10869228.jpg?v=1723753366", Description = "Premium wireless earbuds with noise cancellation."},
                new() { ProductID = 23, ProductName = "JBL Bluetooth Speaker", Price = 99.99m, StockQuantity = 25 , ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7YL9rMWkmPTAenjc9r2Qnv1NThoLhTK6Y5A&s", Description = "Portable speaker with deep bass and high-quality sound." },
                new() { ProductID = 24, ProductName = "Sonos One Smart Speaker", Price = 199.99m, StockQuantity = 15 , ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_897798-MCO53950787380_022023-O.webp", Description = "Voice-controlled smart speaker with rich sound." },
                new() { ProductID = 25, ProductName = "Nikon D3500 DSLR Camera", Price = 499.99m, StockQuantity = 10 , ImageUrl = "https://eoatecnologia.com/cdn/shop/files/1535598024_IMG_1056607.jpg?v=1699992619&width=416", Description = "Entry-level DSLR for high-quality photos and videos." },
                new() { ProductID = 26, ProductName = "GoPro Hero 11 Action Camera", Price = 349.99m, StockQuantity = 8 , ImageUrl = "https://www.artikulos.co/wp-content/uploads/GoPro-HERO-11-Black-en-ARTIKULOS.CO-Foto-1.jpg", Description = "Rugged action camera for capturing extreme moments." },
                new() { ProductID = 27, ProductName = "Canon 50mm f/1.8 Lens", Price = 125.99m, StockQuantity = 20 , ImageUrl = "https://lumen-colombia.com/8337-large_01oslo/canon-50mm.jpg", Description = "Prime lens for sharp, fast, and versatile photography." },
                new() { ProductID = 28, ProductName = "Manfrotto Tripod", Price = 89.99m, StockQuantity = 12 , ImageUrl = "https://cassaimportadores.com/cdn/shop/products/Manfrotto-TrIpode-de-aluminio-Compact-Action-con-cabezal-hibrido_1200x1200.png?v=1634751589", Description = "Durable tripod for steady shots and easy handling." },
                new() { ProductID = 29, ProductName = "SanDisk 64GB SD Card", Price = 19.99m, StockQuantity = 50 , ImageUrl = "https://importacionesarturia.com/wp-content/uploads/2020/04/Memoria-Sandisk-64Gb-de-100mbs-PgBlanca-2.jpg", Description = "High-speed 64GB SD card for fast data transfer." },
                new() { ProductID = 30, ProductName = "PlayStation 5 Console", Price = 499.99m, StockQuantity = 5 , ImageUrl = "https://exitocol.vtexassets.com/arquivos/ids/9154830/consola-sony-playstation-5-ps5-825gb-lector-de-disco.jpg?v=637631028235770000", Description = "Next-gen gaming console with stunning 4K visuals."},
                new() { ProductID = 31, ProductName = "Xbox Series X Console", Price = 499.99m, StockQuantity = 6, ImageUrl = "https://exitocol.vtexassets.com/arquivos/ids/7234188/consola-xbox-series-x-1tb-microsoft.jpg?v=637532554328630000", Description = "Powerful gaming console for a seamless experience."  },
                new() { ProductID = 32, ProductName = "Nintendo Switch", Price = 299.99m, StockQuantity = 15, ImageUrl = "https://imagedelivery.net/4fYuQyy-r8_rpBpcY7lH_A/falabellaCO/126171770_01/w=800,h=800,fit=pad", Description = "Portable gaming console for on-the-go fun."  },
                new() { ProductID = 33, ProductName = "PS5 DualSense Controller", Price = 69.99m, StockQuantity = 22, ImageUrl = "https://cosonyb2c.vtexassets.com/arquivos/ids/345373/PS5_DS_Pshot_A.jpg?v=637363940945300000", Description = "Innovative controller with haptic feedback for PS5." },
                new() { ProductID = 34, ProductName = "Xbox Wireless Headset", Price = 99.99m, StockQuantity = 18, ImageUrl = "https://http2.mlstatic.com/D_NQ_NP_839906-MLU70065296481_062023-O.webp", Description = "Wireless headset for immersive Xbox gaming audio."  },
                new() { ProductID = 35, ProductName = "iRobot Roomba Vacuum", Price = 299.99m, StockQuantity = 14, ImageUrl = "https://www.irobotcolombia.com/wp-content/uploads/2023/01/j7.jpg", Description = "Automated vacuum with smart navigation for cleaning." },
                new() { ProductID = 36, ProductName = "LG Smart Air Conditioner", Price = 599.99m, StockQuantity = 8, ImageUrl = "https://www.lg.com/africa/images/split-air-conditioners/md06099357/gallery/medium02.jpg", Description = "Energy-efficient air conditioner with smart controls." },
                new() { ProductID = 37, ProductName = "Samsung Front Load Washing Machine", Price = 849.99m, StockQuantity = 5, ImageUrl = "https://images.samsung.com/is/image/samsung/p6pim/in/ww80t4040ce-tl/gallery/in-front-loading-washer-ww70t4020cheo-377223-ww80t4040ce-tl-395196808?$650_519_PNG$", Description = "Front load washing machine with fast and efficient cleaning." },
                new() { ProductID = 38, ProductName = "Whirlpool Refrigerator", Price = 1199.99m, StockQuantity = 4, ImageUrl = "https://i5.walmartimages.com/seo/Whirlpool-33-21-cu-ft-Top-Freezer-Refrigerator-in-Monochromatic-Stainless-Steel_83b13732-b9d5-40fd-87ce-9f15a4462f8e.9a4cc30a642274ffb600d70c10c0416b.jpeg", Description = "Spacious refrigerator with adjustable temperature controls." },
                new() { ProductID = 39, ProductName = "Panasonic Microwave Oven", Price = 129.99m, StockQuantity = 25, ImageUrl = "https://www.panasonic.com/content/dam/pim/my/en/NN/NN-ST2/NN-ST253/NN-ST253-Product_ImageGlobal-1_my_en.png", Description = "High-performance microwave oven for quick and easy cooking." }
            });
        }
    }
}
